# Generated by Django 5.1.3 on 2024-11-06 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0003_milestones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='achievement',
        ),
    ]
