# Generated by Django 5.1.3 on 2024-11-06 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0004_remove_step_achievement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='milestones',
            options={},
        ),
        migrations.CreateModel(
            name='MilestonesAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='achievements.achievement')),
            ],
        ),
        migrations.AlterField(
            model_name='milestones',
            name='achievement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='achievements.milestonesachievement'),
        ),
    ]
