# Generated by Django 5.1.3 on 2024-11-06 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0005_alter_milestones_options_milestonesachievement_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='milestones',
            options={'ordering': ['order']},
        ),
        migrations.AlterField(
            model_name='milestones',
            name='achievement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='achievements.achievement'),
        ),
    ]
