# Generated by Django 5.1.3 on 2024-11-06 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0007_remove_milestonesachievement_achievement_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='milestones',
            unique_together={('order', 'achievement')},
        ),
    ]
