# Generated by Django 5.1.3 on 2024-11-06 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0008_alter_milestones_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='achievement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='achievements.achievement'),
        ),
    ]
